In [2]:
import numpy as np

In [3]:
print (np.__version__)

1.13.3


In [4]:
my_list = [-17, 0, 4, 5, 9]
my_array_from_list = np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

In [5]:
my_array_from_list * 10

array([-170,    0,   40,   50,   90])

In [6]:
my_tuple = (14, -3.54, 5+7j)
np.array(my_tuple)

array([ 14.00+0.j,  -3.54+0.j,   5.00+7.j])

### Difference between and python and numpy data structures

In [7]:
my_tuple * 6     # * acts as replicate operator

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [8]:
np.array(my_tuple) * 6   # * acts as the multiplication operator

array([ 84.00 +0.j, -21.24 +0.j,  30.00+42.j])